[package]
name = "fingerprints"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.0"
rustc-serialize = "0.3.24"
crc = "2.0"